/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and is committed so `npm run typecheck`
// also works in a fresh checkout before the first Next.js build.
