'use client';
import {useEffect,useState,useRef} from 'react';
import type {Offer,Item,Response,ComparisonItem} from '../lib/catalog';
import Modal from './modal';
import ThemeControl from './theme-control';
import ResultState from './result-state';
import {recordEvent as event} from '../lib/analytics';
const unavailableMessage='Каталог временно недоступен. Попробуйте ещё раз.';
class SearchError extends Error {}
const languages:Record<string,string>={go:'Go',python:'Python',java:'Java',javascript:'JavaScript'};
const experience:Record<string,string>={none:'Начинаю с нуля',basics:'Знаю основы',projects:'Пишу свои проекты',working:'Работаю разработчиком',switch:'Перехожу с другого языка'};
const goals:Record<string,string>={try:'Попробовать программирование',job:'Подготовиться к первой работе',switch:'Сменить язык / направление',deepen:'Углубить знания'};
const directions:Record<string,string>={basics:'Основы',backend:'Backend',frontend:'Frontend',fullstack:'Fullstack',automation:'Автоматизация'};
function money(i:Item){if(i.effective_price===null)return i.offer.price_kind==='from'?'Цена от · уточните у школы':'Уточнить цену';return i.effective_price===0?'Бесплатно':new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(i.effective_price/100)}
function date(v:string){return new Date(v).toLocaleDateString('ru-RU')}
function support(o:Offer){return o.mentor?'Персональный наставник':o.review?'Проверка заданий':'Самостоятельно'}
function Select({label,name,values,defaultValue}:{label:string;name:string;values:Record<string,string>;defaultValue?:string}){return <label>{label}<select name={name} defaultValue={defaultValue||''}><option value="">Не важно</option>{Object.entries(values).map(([v,t])=><option value={v} key={v}>{t}</option>)}</select></label>}
const searchParameterNames=new Set(['language','direction','experience','goal','budget','support','schedule','sort','min','max','hours','include_free','include_closed','page','page_size']);
const urlParameterNames=new Set([...searchParameterNames,'compare']);
function canonicalParams(source:URLSearchParams){const result=new URLSearchParams();source.forEach((value,key)=>{if(!urlParameterNames.has(key)||!value||key==='sort'&&value==='recent'||key==='page'&&value==='1'||key==='page_size'&&value==='12'||value==='false')return;result.set(key,value)});return result}
function searchParams(source:URLSearchParams){const result=new URLSearchParams();source.forEach((value,key)=>{if(searchParameterNames.has(key))result.set(key,value)});return result}
function countLabel(n:number){const tail=n%100, digit=n%10;return `${n} ${tail>=11&&tail<=14?'программ':digit===1?'программа':digit>=2&&digit<=4?'программы':'программ'}`}
const filterLabels:Record<string,string>={language:'Язык',direction:'Направление',experience:'Опыт',goal:'Цель',budget:'Стоимость',support:'Поддержка',schedule:'Расписание',min:'От',max:'До',hours:'Часов в неделю',include_free:'Бесплатные включены',include_closed:'Закрытый набор включён'};
function filterValue(key:string,value:string){if(key==='min'||key==='max')return new Intl.NumberFormat('ru-RU').format(Number(value)/100)+' ₽';return ({...languages,...experience,...goals,...directions,free:'Бесплатно',paid:'Платные',self:'Самостоятельно',review:'Проверка заданий',mentor:'Наставник',flexible:'В своём темпе',scheduled:'По расписанию',true:'Да'} as Record<string,string>)[value]||value}
export default function Finder({resultsPath='/courses'}:{resultsPath?:string}){
 const [filtersOpen,setFiltersOpen]=useState(false),[formRevision,setFormRevision]=useState(0);
 const [shareURL,setShareURL]=useState(''),[shareStatus,setShareStatus]=useState('');
 const [params,setParams]=useState<URLSearchParams|null>(null),[data,setData]=useState<Response|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 const [selected,setSelected]=useState<string[]>([]),[compare,setCompare]=useState<ComparisonItem[]|null>(null),[compareOpen,setCompareOpen]=useState(false),[modalError,setModalError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{const read=()=>{const raw=new URLSearchParams(location.search),p=canonicalParams(raw),query=p.toString();if(raw.toString()!==query)history.replaceState(null,'',location.pathname+(query?'?'+query:''));setParams(p);setFormRevision(v=>v+1);setSelected((p.get('compare')||'').split(',').filter(Boolean).slice(0,3));setCompareOpen(p.has('compare'))};read();window.addEventListener('popstate',read);return()=>window.removeEventListener('popstate',read)},[]);
 useEffect(()=>{
  if(!params)return;
  const ctrl=new AbortController(),query=searchParams(params).toString();
  setLoading(true);setError('');
  fetch('/api/v1/courses'+(query?'?'+query:''),{signal:ctrl.signal}).then(async r=>{
   if(!r.ok)throw new SearchError(r.status===400?'Проверьте параметры поиска или сбросьте фильтры.':'Каталог временно недоступен. Попробуйте ещё раз.');
   const data=await r.json();
   if(!Array.isArray(data.items)||typeof data.total!=='number')throw new SearchError(unavailableMessage);
   return data;
  }).then((d:Response)=>{
   // Transport may already have completed when cleanup aborts this search.
   // Ignore queued results and analytics as well as late failures.
   if(ctrl.signal.aborted)return;
   setData(d);event(d.total?'search':'empty',{language:params.get('language')||'',goal:params.get('goal')||'',total:d.total});
  }).catch(e=>{if(!ctrl.signal.aborted)setError(e instanceof SearchError?e.message:unavailableMessage)}).finally(()=>{if(!ctrl.signal.aborted)setLoading(false)});
  return()=>ctrl.abort();
 },[params,retry]);
 useEffect(()=>{if(!compareOpen)return;const ctrl=new AbortController();setCompare(null);setModalError('');fetch('/api/v1/compare?offer_ids='+selected.join(','),{signal:ctrl.signal}).then(r=>{if(!r.ok)throw Error('Не удалось загрузить сравнение');return r.json()}).then(setCompare).catch(e=>{if(e.name!=='AbortError')setModalError(e.message)});return()=>ctrl.abort()},[compareOpen,selected]);
 function navigate(raw:URLSearchParams,preserveDraft=false){const p=canonicalParams(raw),query=p.toString();history.pushState(null,'',resultsPath+(query?'?'+query:''));setParams(p);if(!preserveDraft)setFormRevision(v=>v+1)}
 async function copySearch(){const url=location.href;try{if(!navigator.clipboard?.writeText)throw Error('Clipboard unavailable');await navigator.clipboard.writeText(url);setShareURL('');setShareStatus('Ссылка скопирована')}catch{setShareURL(url);setShareStatus('Скопируйте ссылку из поля ниже')}}
 useEffect(()=>{setShareURL('');setShareStatus('')},[params]);
 function search(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),p=new URLSearchParams();const min=String(f.get('min')||''),max=String(f.get('max')||'');if(min&&max&&Number(min)>Number(max)){const input=form.elements.namedItem('max') as HTMLInputElement;input.setCustomValidity('Максимальный бюджет должен быть не меньше минимального.');input.reportValidity();return;}f.forEach((v,k)=>{if(v){p.set(k,k==='min'||k==='max'?String(Math.round(Number(v)*100)):String(v))}});navigate(p);setFiltersOpen(false)}
 function toggle(id:string){setNotice('');setSelected(s=>{if(s.includes(id))return s.filter(x=>x!==id);if(s.length===3){setNotice('В сравнении уже 3 тарифа. Уберите один, чтобы добавить новый.');return s}return [...s,id]})}
 function showCompare(){try{localStorage.setItem('devcourse-offers',JSON.stringify(selected))}catch{};location.assign('/compare?offers='+selected.map(encodeURIComponent).join(','))}
 function close(){setCompareOpen(false);setModalError('');const p=new URLSearchParams(location.search);p.delete('compare');history.replaceState(null,'','?'+p)}
 useEffect(()=>{if(new URLSearchParams(location.search).has('compare'))return;try{const saved=JSON.parse(localStorage.getItem('devcourse-offers')||'[]');if(Array.isArray(saved))setSelected([...new Set(saved.filter((v:unknown):v is string=>typeof v==='string'))].slice(0,3))}catch{}},[]);
 const searchButton=useRef<HTMLButtonElement>(null);
 const items=data?.items||[],page=data?.page||1;
 const hasFilters=Array.from(params?.keys()||[]).some(key=>!['sort','page','page_size','compare'].includes(key));
 return <><header><a className="brand" href="/"><span className="brandIcon">&lt;/&gt;</span>devcourse<span className="brandDot">.</span></a><span className="headerNote">Ваш путь в разработку</span><ThemeControl/><a href="/about" className="quiet">Как мы подбираем</a></header>
 <main><section className="intro"><div className="eyebrow">МЕНЬШЕ ПОИСКА. БОЛЬШЕ ПРАКТИКИ.</div><h1>Учиться тому,<br className="mobileBreak"/> что нужно <span>вам.</span></h1><p>Сравните обучение разработке по опыту, цели и бюджету.<br/>От первого «Hello, world!» до следующего шага в карьере.</p></section>
 <button className="mobileFilters secondary" aria-expanded={filtersOpen} aria-controls="catalog-filters" onClick={()=>setFiltersOpen(v=>!v)}>{filtersOpen?'Скрыть фильтры':'Фильтры'}{hasFilters?' · '+Array.from(params?.keys()||[]).filter(k=>k in filterLabels).length:''}</button>
 <div className="workspace"><aside id="catalog-filters" className={filtersOpen?'filtersOpen':'filtersClosed'}><div className="filterTitle"><h2>Ваш маршрут</h2><button className="textButton" onClick={()=>navigate(new URLSearchParams())}>Сбросить</button></div>
 {params&&<form key={formRevision} onSubmit={search} onChange={e=>{const form=e.currentTarget;const input=form.elements.namedItem('max') as HTMLInputElement;input.setCustomValidity('')}}>
 <fieldset><legend>Язык разработки</legend><div className="languageGrid"><label className="languageChoice"><input type="radio" name="language" value="" defaultChecked={!params.get('language')}/><span>Все языки</span></label>{Object.entries(languages).map(([k,v])=><label className="languageChoice" key={k}><input type="radio" name="language" value={k} defaultChecked={params.get('language')===k}/><span>{v}</span></label>)}</div></fieldset>
 <Select label="Текущий опыт" name="experience" values={experience} defaultValue={params.get('experience')||''}/>
 <Select label="Ваша цель" name="goal" values={goals} defaultValue={params.get('goal')||''}/>
 <Select label="Стоимость" name="budget" values={{free:'Только бесплатно',paid:'Платные программы'}} defaultValue={params.get('budget')||''}/>
 <div className="priceInputs"><label>От, ₽<input name="min" type="number" min="0" max="100000000" placeholder="0" defaultValue={params.has('min')?Number(params.get('min'))/100:''}/></label><label>До, ₽<input name="max" type="number" min="0" max="100000000" placeholder="Без лимита" defaultValue={params.has('max')?Number(params.get('max'))/100:''}/></label></div><small>Полная стоимость обучения, не платёж в месяц.</small>
 <label className="checkbox"><input type="checkbox" name="include_free" value="true" defaultChecked={params.get('include_free')==='true'}/>Добавить бесплатные к платным</label>
 <details><summary>Больше параметров <span>+</span></summary><Select label="Направление" name="direction" values={directions} defaultValue={params.get('direction')||''}/><Select label="Обратная связь" name="support" values={{self:'Самостоятельно',review:'Проверка заданий',mentor:'Наставник'}} defaultValue={params.get('support')||''}/><Select label="Расписание" name="schedule" values={{flexible:'В своём темпе',scheduled:'По расписанию'}} defaultValue={params.get('schedule')||''}/><label>Часов в неделю, не больше<input name="hours" type="number" min="1" max="168" defaultValue={params.get('hours')||''}/></label><label className="checkbox"><input type="checkbox" name="include_closed" value="true" defaultChecked={params.get('include_closed')==='true'}/>Показать закрытый и неизвестный набор</label></details>
 <input type="hidden" name="sort" value={params.get('sort')||'recent'}/><button ref={searchButton} className="primary searchButton" type="submit">Найти обучение <span>→</span></button></form>}</aside>
 <section className="results" aria-label="Результаты поиска" aria-busy={loading}><div className="resultsHeading"><div><div className="eyebrow">КАТАЛОГ ОБУЧЕНИЯ</div><h2>{loading?'Ищем подходящие программы…':error?'Поиск недоступен':data?.total?countLabel(data.total)+' по вашим условиям':hasFilters?'Пока без совпадений':'Каталог пока пуст'}</h2></div><label className="sort">Сортировка<select aria-label="Сортировка" value={params?.get('sort')||'recent'} onChange={e=>{const p=new URLSearchParams(params||'');p.set('sort',e.target.value);p.delete('page');navigate(p,true)}}><option value="recent">Сначала свежие данные</option><option value="price_asc">Сначала дешевле</option><option value="price_desc">Сначала дороже</option><option value="duration">Сначала короче</option></select></label></div>
 <div className="resultActions"><div className="filterChips" aria-label="Применённые фильтры">{Array.from(params?.entries()||[]).filter(([key])=>key in filterLabels).map(([key,value])=><button className="filterChip" key={key} aria-label={"Убрать фильтр: "+filterLabels[key]} onClick={()=>{const p=new URLSearchParams(params||'');p.delete(key);p.delete('page');navigate(p)}}>{filterLabels[key]}: {filterValue(key,value)} <span aria-hidden="true">×</span></button>)}</div><div className="shareSearch"><button className="textButton" onClick={copySearch}>Скопировать ссылку</button>{shareStatus&&<p role="status">{shareStatus}</p>}{shareURL&&<label>Ссылка на поиск<input readOnly autoFocus value={shareURL} onFocus={e=>e.currentTarget.select()}/></label>}</div></div>
 <div className="trustLine"><span>✓ Бесплатные и платные</span><span>✓ Без регистрации</span><span>✓ Сравнение тарифов</span></div>
 {items.some(i=>i.course.demo)&&<div className="demoBanner"><strong>Демонстрационный каталог.</strong> Названия и цены — примеры для проверки сайта, не реальные предложения школ.</div>}
 {notice&&<div role="status" className="demoBanner">{notice}</div>}
 {loading?<div className="skeletons" aria-label="Загрузка">{[1,2,3].map(n=><div key={n} className="skeleton"/>)}</div>:error?<ResultState kind="error" message={error} onRetry={()=>setRetry(x=>x+1)} onReset={()=>navigate(new URLSearchParams())}/>:!items.length?<ResultState kind={hasFilters?"filtered":"empty"} onRetry={()=>setRetry(x=>x+1)} onReset={()=>navigate(new URLSearchParams())}/>:<div className="cards">{items.map(i=><article className="card" key={i.course.id}><div className="cardTop"><span className={'languageBadge '+i.course.language}>{languages[i.course.language]}</span><span className="provider">{i.course.provider}</span>{i.course.demo&&<span className="miniBadge">ДЕМО</span>}</div><div className="cardBody"><div className="courseInfo"><div className="courseDirection">{directions[i.course.direction]} · {i.offer.schedule==='flexible'?'В своём темпе':i.offer.schedule==='scheduled'?'По расписанию':'Расписание уточняется'}</div><h3><a className="titleButton" href={"/courses/"+encodeURIComponent(i.course.slug)}>{i.course.title}</a></h3><p>{i.course.summary}</p><div className="facts"><span>◷ {i.offer.weeks?i.offer.weeks+' нед.':'Срок не указан'}</span><span>{i.offer.hours?i.offer.hours+' ч/нед.':'Нагрузка не указана'}</span><span>{support(i.offer)}</span></div><div className="reasons">{i.reasons?.map(r=><span key={r}>✓ {r}</span>)}</div></div><div className="offerInfo"><span className="tariff">{i.offer.name}</span>{i.offer.enrollment==='closed'&&<span className="miniBadge">Набор закрыт</span>}{i.offer.enrollment==='unknown'&&<span className="miniBadge">Набор неизвестен</span>}<strong className={i.effective_price===0?'price free':'price'}>{money(i)}</strong><small>{i.effective_price!==null&&i.effective_price>0?'за весь курс':'Условия на сайте источника'}</small><a className="secondary linkButton" href={"/courses/"+encodeURIComponent(i.course.slug)}>Подробнее ↗</a><label className="checkbox"><input type="checkbox" checked={selected.includes(i.offer.id)} onChange={()=>toggle(i.offer.id)}/>Сравнить тариф</label></div></div><div className="cardFooter"><span>Проверено {date(i.course.checked_at)}{i.stale?' · Данные требуют обновления':''}</span><a href={i.course.source} target="_blank" rel="noopener noreferrer">Источник ↗</a></div></article>)}</div>}
 {!loading&&!error&&data&&data.total>data.page_size&&<nav className="pagination" aria-label="Страницы"><button disabled={page===1} onClick={()=>{const p=new URLSearchParams(params||'');p.set('page',String(page-1));navigate(p,true)}}>← Назад</button><span>{page} / {Math.ceil(data.total/data.page_size)}</span><button disabled={page*data.page_size>=data.total} onClick={()=>{const p=new URLSearchParams(params||'');p.set('page',String(page+1));navigate(p,true)}}>Далее →</button></nav>}
 </section></div>
 <section id="how" className="how"><div><div className="eyebrow">ПОНЯТНЫЙ ВЫБОР</div><h2>Условия важнее обещаний.</h2></div><p>Мы сравниваем конкретные тарифы и полную стоимость. Если цена устарела или неизвестна, показываем это явно и не включаем программу в поиск с ограничением бюджета. Переход и запись — на сайте источника. Каталог не гарантирует трудоустройство.</p></section></main>
 <footer><a className="brand" href="/">devcourse.</a><span>Учиться — ваш выбор. Найти — наша задача.</span><span>MVP · 2026</span></footer>
 {selected.length>0&&!compareOpen&&<div className="compareBar"><span><strong>{selected.length} из 3</strong> тарифов для сравнения</span><button className="primary" onClick={showCompare}>Сравнить →</button><button className="textButton" onClick={()=>setSelected([])}>Очистить</button></div>}
 {(compareOpen||modalError)&&<Modal label="Сравнение тарифов" onClose={close} fallbackFocus={searchButton}>
 {modalError?<p role="alert">{modalError}</p>:<><div className="eyebrow">ВАШ КОРОТКИЙ СПИСОК</div><h2>Сравнение тарифов</h2><p>Одинаковые критерии — осознанный выбор. Ссылка на эту страницу сохраняет сравнение.</p>{!compare?<p role="status">Загрузка…</p>:<div className="tableWrap" role="region" aria-label="Сравнение тарифов, горизонтальная прокрутка" tabIndex={0}><table><thead><tr><th scope="col">Условия</th>{compare.map((i,n)=><th scope="col" key={n}>{i.unavailable?(i.reason==='closed'?'Набор закрыт — предложение недоступно':'Предложение недоступно'):i.course.title}</th>)}</tr></thead><tbody>{['Тариф','Полная стоимость','Срок','Нагрузка','Поддержка','Проверено','Действия'].map((row,r)=><tr key={row}><th scope="row">{row}</th>{compare.map((i,n)=><td key={n}>{i.unavailable?'—':r===0?i.offer.name:r===1?money(i):r===2?(i.offer.weeks?i.offer.weeks+' нед.':'Не указано'):r===3?(i.offer.hours?i.offer.hours+' ч/нед.':'Не указано'):r===4?support(i.offer):r===5?date(i.course.checked_at):<a className="primary linkButton" href={'/out/'+i.offer.id} target="_blank" rel="noopener noreferrer">На сайт источника ↗</a>}</td>)}</tr>)}</tbody></table></div>}</>}
 </Modal>}</>
}
