import type {Metadata} from 'next';
import {socialMetadata} from '../../../lib/social-metadata';
import {course} from '../../../lib/api';
import {price,checked,profiles} from '../../../lib/catalog';
import CatalogActions from '../../catalog-actions';
import ExternalMark from '../../external-mark';
type Props={params:Promise<{slug:string}>};
export const dynamic='force-dynamic';
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const d=await course(slug);return socialMetadata(d.course.title+' — DevCourse',d.course.summary,'/courses/'+encodeURIComponent(slug))}
export default async function CoursePage({params}:Props){const d=await course((await params).slug);const c=d.course;
 return <main className="document"><nav><a href="/courses">← Каталог</a> · <a href="/about">О сервисе</a></nav><h1>{c.title}</h1><p>{c.provider} · {c.language}</p>{c.demo&&<p className="demoBanner">Демонстрационная программа: название и условия вымышлены.</p>}<p>{c.summary}</p><h2>Кому подходит</h2><p>{c.audience.map(v=>profiles[v]||v).join(' · ')}</p><p>Подробные требования к подготовке уточняйте в программе поставщика.</p><h2>Содержание</h2><ul>{c.topics.map(t=><li key={t}>{t}</li>)}</ul><h2>Тарифы</h2><div className="detailOffers">{d.offers.map(i=><section key={i.offer.id}><h3>{i.offer.name}</h3><strong className="price">{price(i)}</strong><p>Цена проверена: {checked(i.offer.price_checked_at)}. {i.effective_price===null&&'Цена неизвестна, устарела или указана «от». Уточните полную стоимость у поставщика.'}</p><p>Длительность: {i.offer.weeks===null?'Не указана':i.offer.weeks+' недель'}. Нагрузка: {i.offer.hours===null?'Не указана':i.offer.hours+' ч/нед.'}.</p><p>Проверка кода: {i.offer.review?'Есть':'Нет'}. Индивидуальные занятия: {i.offer.mentor?'Есть':'Нет'}.</p><p>Расписание: {i.offer.schedule==='flexible'?'Свободное':i.offer.schedule==='scheduled'?'По расписанию':'Неизвестно'}.</p><p>Набор: {({open:'Открыт',continuous:'Постоянный',closed:'Закрыт',unknown:'Неизвестен'} as Record<string,string>)[i.offer.enrollment]}</p>{['open','continuous'].includes(i.offer.enrollment)&&<CatalogActions id={i.offer.id}/>}<a className="primary linkButton" href={'/out/'+encodeURIComponent(i.offer.id)} target="_blank" rel="noopener noreferrer">{['open','continuous'].includes(i.offer.enrollment)?'На сайт курса':'Проверить набор'}</a></section>)}</div><h2>Источники</h2><a href={c.source} target="_blank" rel="noopener noreferrer">Опубликованная программа поставщика <ExternalMark/></a><p>Условия проверены {checked(c.checked_at)}. Проверка опубликованной программы не означает прохождение курса. Срок доступа и ограничения тарифа уточняйте у поставщика.</p></main>;
}
